mutation createMessage($text: String!) {
    createMessage(text: $text){
        id
        room{
            name
        }
        author{
            id
            username
        }
        text
    }
}